[package]
name = "raytracer_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24.8", features = ["png"] }
indicatif = { version = "0.17.7", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.8.0"
