pub mod bouncing_spheres;
pub mod bouncing_spheres_with_light;
pub mod checkered_spheres;
pub mod cornell_box;
pub mod earth;
pub mod empty_cornell_box;
pub mod quads;
pub mod scene;
pub mod simple_light;
